.TH TILT 1
.SH NAME
tilt, tilt-nj, tilt-slaves \- Standard ML compiler
.SH SYNOPSIS
.B tilt
[
.I option ...
]
.I project ...
.PP
.B tilt
[
.I option ...
]
.B -o
.I exe project ...
.PP
.B tilt
[
.I option ...
]
.B -l
.I lib project ...
.PP
.B tilt
[
.I option ...
]
.BR -p [ p ]
.I project ...
.PP
.B "tilt -s"
.PP
.B tilt-slaves
[
.B -n
]
.RI [ num /] host
.I ...
.SH DESCRIPTION
TILT is a compiler for Standard ML (SML) that uses Typed Intermediate
Languages.  It can make executables and libraries for the SPARC V9 and
Alpha architectures running SunOS 5.5.1, SunOS 5.7, SunOS 5.8, and
Digital Unix V4.0D.
.I Tilt
is a version of the compiler compiled by TILT.
.I Tilt-nj
is a version of the compiler compiled by Standard ML of New Jersey; it
should run on any Unix system supported by SML/NJ.
.PP
TILT operates on a project description accreted from the named
.I project
files.  A project description assigns logical names to compilation
units and their interfaces and describes the dependencies between them.  By
default, TILT performs incremental recompilation (IR) to bring every unit
and interface in the project description up to date.  The options are
.PD 0
.TP
.BI -o " exe"
Perform IR and link every unit into an
executable
.IR exe .
This fails if there are unimplemented units.
.TP
.BI -l " lib"
Perform IR and pack every unit and interface into a library
.IR lib .
.TP
.B -p
Purge
(remove) object files for every source unit in
the project description.
With a second
.BR -p ,
purge all compiler-generated files for every source unit and source
interface.  Files associated with compiled units and interfaces (ie, library files)
are not removed.
.TP
.B -s
Act as a slave for any future or ongoing parallel make in the current
directory.  When a slave joins a parallel make, the TILT process that
initiated compilation (the master) sends the target architecture,
compiler flags, and project description to the slave.
.TP
.B -v
Make TILT more verbose.  This option can be repeated.
.TP
.BI -f " F"
Set the compiler flag
.I F
to true; these flags are undocumented.
.TP
.BI -r " F"
Set
.I F
to false.
.TP
.B -m
Prevent TILT from forking off a slave process to handle compilation.
Compilation will proceed when slaves are started (with
.BR "tilt -s" )
in the current directory.
.TP
.BI -c " U"
Operate on unit
.IR U .
.TP
.BI -C " I"
Operate on interface
.IR I .
The
.B -c
and
.B -C
options can be repeated to specify a list of
.IR roots .
TILT will operate on a reduced project description
obtained by discarding
any units and interfaces that are not prerequisite to
.IR roots .
.TP
.BI -t " T"
Set the target architecture;
.I T
must be
.B sparc
or
.BR alpha .
The default is the current architecture, if it is supported, and
.B sparc
otherwise.
.PD
.PP
.I Tilt-slaves
launches
.I num
slaves on
.I host
using
.I tilt
(or
.I tilt-nj
if the
.B -n
option is present).
.SS Make system
.SS Program execution
.SS Libraries
.SH EXAMPLES
.SH SEE ALSO
.IR project (6)
